app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):

    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key =True)
    username = db.Column(db.String(255))
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    email = db.Column(db.String(255),unique = True,index = True)
    password_hash = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    pitchs = db.relationship('Pitch',backref = 'pitchs',lazy = "dynamic")
    feedbacks = db.relationship('Feedback',backref='feedbacks',lazy="dynamic")

    @property
    def password(self):

        raise AttributeError('You cannot read the password attributes')

    @password.setter
    def password(self, password):

        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):

        return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        return f'User {self.username}'

class Role(db.Model):

    __tablename__ = 'roles'
    id = db.Column(db.Integer,primary_key =True)
    name = db.Column(db.String(255))
    user_id = db.relationship('User',backref = 'role',lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'


class Pitch(UserMixin,db.Model):

    __tablename__ = 'pitchs'

    id = db.Column(db.Integer, primary_key=True)
    post = db.Column(db.String(255))
    body = db.Column(db.String(1000))
    category = db.Column(db.String(1000))
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    feedbacks = db.relationship('Feedback',backref = 'pitch',lazy = "dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

class Feedback(UserMixin,db.Model):

    __tablename__ = 'feedbacks'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    feedback = db.Column(db.String(1000))
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    pitch_id = db.Column(db.Integer, db.ForeignKey("pitchs.id"))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))


    def save_feedback(self):
        db.session.add(self)
        db.session.commit()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class FeedbackForm(FlaskForm):

    title = StringField('Feedback title',validators=[Required()])

    feedback = TextAreaField('Pitch feedback', validators=[Required()])

    submit = SubmitField('Submit')


class PitchForm(FlaskForm):
    post = StringField('Your name',validators=[Required()])
    body = TextAreaField('Pitch')
    category = SelectField('Pick Category',
    
    choices=[('INTERVIEW', 'INTERVIEW'),
    ('PRODUCT', 'PRODUCT'),
    ('PROMOTION', 'PROMOTION'),
    ('PICK-UP', 'PICK-UP'),
    ('COMEDY', 'COMEDY')],
    validators=[Required()])
    submit = SubmitField('Pitch')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail


mail = Mail()
bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()

login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):


    app = Flask(__name__)

    app.config.from_object(config_options[config_name])

    bootstrap.init_app(app)

    db.init_app(app)

    mail.init_app(app)

    login_manager.init_app(app)
    from .auth import auth as auth_blueprint
    from .main import main as main_blueprint


    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    app.register_blueprint(main_blueprint)

    # from .request import configure_request
    # configure_request(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from flask_login import login_required
from ..models import User,Feedback,Pitch
from .forms import FeedbackForm,PitchForm
from .. import db

# landing
@main.route('/')
def index():
    '''
    View root page function that returns index page and its data
    '''
    title = 'Pitcher'

    return render_template('index.html', title = title)

# post pitch
@main.route('/new_pitch', methods = ['GET','POST'])
@login_required
def new_pitch():
    form = PitchForm()
    if form.validate_on_submit():
        pitch = Pitch(post=form.post.data,body=form.body.data,category=form.category.data)
        pitch.save_pitch()
        return redirect(url_for('main.index'))
    return render_template('new_pitch.html',form=form)

# profile
@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    index=Pitch.query.all()
    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user,index = index)

# feedback
@main.route('/feedback', methods = ['GET','POST'])
@login_required
def new_feedback(id):
    form = FeedbackForm()
    pitch = Pitch.query.get(id)
    if form.validate_on_submit():
        feedback = Feedback(title=form.title.data,feedback=form.feedback.data, pitch=pitch)
        db.session.add(feedback)
        db.session.commit()
    feed_back = Feedback.query.filter_by(pitch=pitch).all()
    return render_template('feedback.html',feed_back=feed_back,form=form)


# product
@main.route('/product', methods = ['GET','POST'])
@login_required
def product():
    product_pitch=Pitch.query.filter_by(category="PRODUCT")
    return render_template('product.html', product_pitch = product_pitch)

# pick_Up
@main.route('/pick_up', methods = ['GET','POST'])
@login_required
def pick():
    pick_Up=Pitch.query.filter_by(category="PICK-UP")
    return render_template('pick_up.html', pick_Up = pick_Up)

# stand up comedy
@main.route('/stand_up_comedy', methods = ['GET','POST'])
@login_required
def stand():
    stand_Up=Pitch.query.filter_by(category="COMEDY")
    return render_template('stand_up_comedy.html', stand_Up = stand_Up)

# PROMOTION
@main.route('/promotion', methods = ['GET','POST'])
@login_required
def promotion():
    promotion_pitch=Pitch.query.filter_by(category="PROMOTION")
    return render_template('promotion.html', promotion_pitch = promotion_pitch)

# INTERVIEW
@main.route('/interview', methods = ['GET','POST'])
@login_required
def interview():
    interview_pitch=Pitch.query.filter_by(category="INTERVIEW")
    return render_template('interview.html', interview_pitch = interview_pitch)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{{ wtf.quick_form(form) }}

app/templates/feedback.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

{{ wtf.quick_form(fom) }}

{% for feedback in feed_back %}

<p>{{ feedback.feedback }}</p>
<p> By: {{feedback.title}}</p>

{% endfor %}

{% endblock %}

app/templates/index.html
{% extends 'base.html'%}

{% block content %}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
<link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
{% endblock%}

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-1">

      </div>
      <div class="col-md-10">
        <div class="home">
          <h1><strong>PITCHER</strong></h1>
          <h2><strong>Pitch your ideas!</strong></h2>
          <h6><strong>Get Pitch ideas or write your own. Be the insiration you are!</strong></h6>
          <a class="btn btn-success btn-lg text-center"> Profile</a>
        </div>
        <div class="row">
          <div class="imgs">
            <br>
            <br>
            <br>
            <img src="https://image.shutterstock.com/image-vector/vinnitsa-ukraine-april-03-2018-260nw-1184346502.jpg" alt="fb" height="50px"width="50px">
            <img src="https://cdn.pixabay.com/photo/2016/08/09/17/52/instagram-1581266__340.jpg" alt="twiter" height="50px"width="50px">
            <img src="https://www.glassmanwealth.com/wp-content/uploads/2015/10/alltwitter-twitter-bird-logo-white-on-blue.png" alt="insta" height="50px"width="50px">
          </div>
        </div>
      </div>
      <div class="col-md-1">

      </div>
    </div>
  </div>
</body>

<style>
.home{
    font-family:  'Bree Serif', serif;
    font:20px;
    font-size: 60px;
    color: white;
    text-align:justify;
    margin-left:30%;
    margin-top:10%;
}
body{
  background-image:url('https://images.pexels.com/photos/33045/lion-wild-africa-african.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940')
}
img{
  border-radius:50%;
  margin-left:20%;
  margin-bottom:10%;
}
</style>
{%endblock%}

app/templates/interview.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<h1>Interview Pitches</h1>
{% if interview_pitch %}
{% for pitch in interview_pitch %}

<div class="card">
  <p>{{pitch.body}}</p>
  <p>By:{{pitch.post}}</p>
  <p>{{pitch.date_posted}}</p>
</div>

{% endfor %}
<a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>

{% else%}
<h3 class="text-center">No pitches yet</h3>


<a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>
{% endif %}

<h3>Feedback</h3>
{% for feedback  in feed_back %}
{{feedback.title}}
By:{{ feedback.feedback }}

{% endfor %}

<style>
.card{
    padding: 10px;
    padding-top: 0;
    border: 1px solid black;
    box-shadow: -1px 1px 16px -1px rgba(0, 0, 0, 0.75);
    margin: 10px;
    overflow: hidden;
    transition: transform 1s;
    opacity: 10px;
  }
</style>
{% endblock%}

app/templates/marcos.html
{% macro displayPitchs(pitch_list) %}
    {% for pitch in pitch_list %}

        <p> {{ pitch.pitch }}</p>
    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" style="background-color: #0B3948;" role="navigation">
  <div class="container-fluid">
    <br>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"> PITCHER</a>
    </div>
    <ul class="nav navbar-nav navbar-right" style="background-color: #0B3948;">
      {% if current_user.is_authenticated %}
      <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
      <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
      {% else %}
      <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
      {%endif%}
    </ul>
    <div class="bar">
    <div class="navbar-collapse collapse" style="background-color: #0B3948;">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">HOME</a></li>
        <li><a href="/interview">INTERVIEW PITCH</a></li>
        <li><a href="/product">PRODUCT PITCH</a></li>
        <li><a href="/promotion">PROMOTION PITCH</a></li>
        <li><a href="/pick_up">PICK UP LINES</a></li>
        <li><a href="/stand_up_comedy">STAND UP COMEDIES</a></li>

    </div>
    </div>
    <br>

  </div>
</div>
<style>
.bar{
    font-family: 'ZCOOL KuaiLe', cursive;
    font:10px;
    font-size: 20px;
    color: green;
}

</style>

app/templates/new_feedback.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">

  <div class="col-md-8">

    <!-- <img src="{{users.profile_pic_path}}" alt="{{users.username}}" class="img-responsive"> -->
  </div>

  <div class="col-md-4">

    {{ wtf.quick_form(feedback_form) }}
  </div>

</div>

{% endblock %}

app/templates/new_pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<div class="container">
    {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/templates/pick_up.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<h1>Pick-Up Pitches</h1>
{% if pick_Up %}
{% for pitch in pick_Up %}

<p>{{pitch.body}}</p>
<p>By:{{pitch.post}}</p>
<p>{{pitch.date_posted}}</p>


{% endfor %}

<a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>

{% else%}
<h3 class="text-center">No pitches yet</h3>


<a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>
{% endif %}


{% endblock%}

app/templates/product.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<h1>Product Pitches</h1>
<a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>
{% if product_pitch %}
{% for pitch in product_pitch %}

<div class="card">

  <p>{{pitch.body}}</p>
  <p>By:{{pitch.post}}</p>
  <p>{{pitch.date_posted}}</p>
</div>

{% endfor %}
{% endif %}


<style>
.card{
    padding: 10px;
    padding-top: 0;
    border: 1px solid black;
    box-shadow: -1px 1px 16px -1px rgba(0, 0, 0, 0.75);
    margin: 10px;
    overflow: hidden;
    transition: transform 1s;
  }
</style>
{% endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
  <div class="row">
    <!-- displaying  Username-->
    <div class="col-md-10">
      <h3> Hello {{user.username| capitalize}} these are the available pitches </h3>

      <!--Displaying user piches-->
      {% for pitch in index %}
      <div class="card">
        <h3>Category: {{pitch.category}}</h3>
        <h3>{{pitch.body}}</H3>
        <p>By:{{pitch.post}}</p>
        <p>Posted at {{pitch.date_posted}}</p>
        <p><a href="/feedback">leave feedback</a></p>
      </div>
      {% endfor %}
    </div>

    <!--Display profile photo-->
    <div class="col-md-2">

      {% if user.profile_pic_path %}
      <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
      {%else%}
      <p>No profile picture</p>
      {% endif %}
    </div>
  </div>
</div>

<style>
  .card {
    padding: 10px;
    padding-top: 0;
    border: 1px solid black;
    box-shadow: -1px 1px 16px -1px rgba(0, 0, 0, 0.75);
    margin: 10px;
    overflow: hidden;
    transition: transform 1s;
  }
</style>
{% endblock %}

app/templates/promotion.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<h1>Promotion Pitches</h1>
{% if promotion_pitch %}
{% for pitch in promotion_pitch %}

<div class="card">
  <p>{{pitch.body}}</p>
  <p>By:{{pitch.post}}</p>
  <p>{{pitch.date_posted}}</p>
</div>

{% endfor %}
<a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>

{% else%}
<h3 class="text-center">No pitches yet</h3>


<a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>
{% endif %}
<style>
.card{
    padding: 10px;
    padding-top: 0;
    border: 1px solid black;
    box-shadow: -1px 1px 16px -1px rgba(0, 0, 0, 0.75);
    margin: 10px;
    overflow: hidden;
    transition: transform 1s;
  }
</style>
{% endblock%}

app/templates/stand_up_comedy.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<h1>Pick-Up Pitches</h1>
{% if stand_Up %}
{% for pitch in stand_Up %}

<div class="card">
  <p>{{pitch.body}}</p>
  <p>By:{{pitch.post}}</p>
  <p>{{pitch.date_posted}}</p>

</div>
{% endfor %}
<a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>

{% else%}
<h3 class="text-center">No pitches yet</h3>


<a class="btn btn-success btn-lg text-center" href="/new_pitch"> Add a new pitch</a>
{% endif %}

.card{
    padding: 10px;
    padding-top: 0;
    border: 1px solid black;
    box-shadow: -1px 1px 16px -1px rgba(0, 0, 0, 0.75);
    margin: 10px;
    overflow: hidden;
    transition: transform 1s;
  }
</style>
{% endblock%}